services:
  postgres:
    image: postgres:16-alpine
    container_name: prisma-pg-json-test
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - '5435:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U testuser -d testdb']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: